# Generated by Django 4.0.3 on 2022-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdata',
            name='classification',
            field=models.CharField(default='default', max_length=7),
        ),
        migrations.AlterField(
            model_name='calcul',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calcul',
            name='file',
            field=models.IntegerField(),
        ),
    ]
