# Generated by Django 4.0.3 on 2022-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdata',
            name='antiquity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='climatic_zone',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='indicator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='value1',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='value2',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='value3',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
